image: home.rniapps.net:28081/rni-infra/torch:py36

cache:
    paths:
        - .cache/pip
        - venv/

before_script:
    - python3 -V
    - pip3 --default-timeout=3000 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 --default-timeout=3000 install -r requirements.txt

pretraining:
    script:
        - python3 download_roberta.py /data/roberta-base
    tags:
        - CPU_COMPUTE_Q4
    only:
        - main
    when: manual
