image: nvcr.io/nvidia/pytorch:20.12-py3

cache:
    paths:
        - .cache/pip
        - venv/

before_script:
    - python3 -V
    - pip3 --default-timeout=3000 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 --default-timeout=3000 install -r requirements.txt

pretraining:
    script:
        - python3 pretrain_roberta.py /data/U2D2P2I/PrivaSeer /data/U2D2P2I/PrivaSeer_Demoset /data/roberta-base /data/pretraining-on-privaseer/logs /data/pretraining-on-privaseer/checkpoints
    tags:
        - One_16GB_GPU
    only:
        - main
        - master

    when: manual
